use native mm instead of inches
ua-snap/rasdaman-ingest pull request #36
Opened 2022-06-14 03:43 UTC by charparr

This PR represents a reprocessing and re-ingest of the snowfall data that drive the snowfall plate in the Arctic-EDS. The motivation was to serve SI units over the API and to do some validation to be sure that the numbers coming out of the client and the API match the values directly extracted from the GeoTIFF sources. It may be hard to see the diffs in the processing notebook, but the key changes are:

 - I’ve changed the GeoTIFF format to float32 from Int16
 - I’ve removed the code snippet that converted from mm to inches.
 - I extracted the min-max-mean historical and projected values for Fairbanks, Anchorage, (using GVV coordinates) and the example lat-lon used in the API documentation. These values can easily be referenced as changes are made to the Arctic-EDS client.

Notes
 - these data are ingested as 'mean_annual_snowfall_mm' on Apollo
 - the API has already been updated to reflect the changes in this PR
 - XREF #34 
 - XREF https://github.com/ua-snap/data-api/pull/200
 - XREF https://github.com/ua-snap/arctic-eds/pull/73
 - Closes #35

2022-06-22 03:24 UTC, kyleredilla requested changes
These changes are all looking good! There is one thing that needs fixing in the ingest recipe file, and I had some minor suggestions for the processing notebook. The processing notebook works well and the addition of sample test point extractions to crosscheck with the API endpoint is very valuable (and checked out after my test processing and ingest!)

2022-06-22 03:24 UTC, kyleredilla commented on arctic_eds/annual_mean_snowfall/annual_mean_swe_preprocessing.ipynb
> +    "    print(\"Historical: \", mmm_summarize(p))\n"
```suggestion
    "    print(\"Projected: \", mmm_summarize(p))\n"
```

2022-06-22 18:43 UTC, charparr commented on arctic_eds/annual_mean_snowfall/annual_mean_swe_preprocessing.ipynb
> +    "scratch_dir = \"/atlas_scratch/cparr4/eds_snowfall/swe_decadal_mean_monthly_total_mm_cru_TS31\"\n",
Kyle I agree that defining the `scratch_dir` once is best! And TBH I sort of butchered the directory structure because I was moving too fast. I like your approach - it makes it easier to pass the notebooks back and forth. I'm going to commit all these suggestions.

2022-06-23 23:23 UTC, kyleredilla approved these changes

2022-06-23 23:23 UTC, kyleredilla commented
Things are looking good now! Merging.

2022-06-23 23:23 UTC, merged